from __future__ import annotations

import time
from datetime import datetime, timedelta

NODE_TYPE_ID_ESP_EASY_STD = 1
NODE_TYPE_ID_RPI_EASY_STD = 5
NODE_TYPE_ID_ESP_EASYM_STD = 17
NODE_TYPE_ID_ESP_EASY32_STD = 33
NODE_TYPE_ID_ESP_EASY32S2_STD = 34
NODE_TYPE_ID_ESP_EASY32C3_STD = 35
NODE_TYPE_ID_ESP_EASY32S3_STD = 36
NODE_TYPE_ID_ESP_EASY32C2_STD = 37
NODE_TYPE_ID_ESP_EASY32H2_STD = 38
NODE_TYPE_ID_ESP_EASY32C6_STD = 39
NODE_TYPE_ID_ESP_EASY32C61_STD = 40
NODE_TYPE_ID_ESP_EASY32C5_STD = 41
NODE_TYPE_ID_ESP_EASY32P4_STD = 42
NODE_TYPE_ID_ESP_EASY32H21_STD = 43
NODE_TYPE_ID_ESP_EASY32H4_STD = 44
NODE_TYPE_ID_ESP_EASY32P4r3_STD = 45
NODE_TYPE_ID_ESP_EASY32S31_STD = 46
NODE_TYPE_ID_ARDUINO_EASY_STD = 65
NODE_TYPE_ID_NANO_EASY_STD = 81

NODE_TYPE_NAMES: dict[int, str] = {
    NODE_TYPE_ID_ESP_EASY_STD: "ESP Easy",
    NODE_TYPE_ID_RPI_EASY_STD: "Rpi Easy",
    NODE_TYPE_ID_ESP_EASYM_STD: "ESP Easy Mega",
    NODE_TYPE_ID_ESP_EASY32_STD: "ESP Easy 32",
    NODE_TYPE_ID_ESP_EASY32S2_STD: "ESP Easy 32-S2",
    NODE_TYPE_ID_ESP_EASY32C3_STD: "ESP Easy 32-C3",
    NODE_TYPE_ID_ESP_EASY32S3_STD: "ESP Easy 32-S3",
    NODE_TYPE_ID_ESP_EASY32C2_STD: "ESP Easy 32-C2",
    NODE_TYPE_ID_ESP_EASY32H2_STD: "ESP Easy 32-H2",
    NODE_TYPE_ID_ESP_EASY32C6_STD: "ESP Easy 32-C6",
    NODE_TYPE_ID_ESP_EASY32C61_STD: "ESP Easy 32-C61",
    NODE_TYPE_ID_ESP_EASY32C5_STD: "ESP Easy 32-C5",
    NODE_TYPE_ID_ESP_EASY32P4_STD: "ESP Easy 32-P4",
    NODE_TYPE_ID_ESP_EASY32H21_STD: "ESP Easy 32-H21",
    NODE_TYPE_ID_ESP_EASY32H4_STD: "ESP Easy 32-H4",
    NODE_TYPE_ID_ESP_EASY32P4r3_STD: "ESP Easy 32-P4r3",
    NODE_TYPE_ID_ESP_EASY32S31_STD: "ESP Easy 32-S31",
    NODE_TYPE_ID_ARDUINO_EASY_STD: "Arduino Easy",
    NODE_TYPE_ID_NANO_EASY_STD: "Nano Easy",
}

DEVICE_TYPE_SINGLE = 1
DEVICE_TYPE_DUAL = 2
DEVICE_TYPE_TRIPLE = 3
DEVICE_TYPE_ANALOG = 10
DEVICE_TYPE_I2C = 20
DEVICE_TYPE_SERIAL = 21
DEVICE_TYPE_SERIAL_PLUS1 = 22
DEVICE_TYPE_SPI = 23
DEVICE_TYPE_SPI2 = 24
DEVICE_TYPE_SPI3 = 25
DEVICE_TYPE_CUSTOM0 = 30
DEVICE_TYPE_CUSTOM1 = 31
DEVICE_TYPE_CUSTOM2 = 32
DEVICE_TYPE_CUSTOM3 = 33
DEVICE_TYPE_USB = 40
DEVICE_TYPE_DUMMY = 99

DEVICE_TYPE_CATEGORIES: dict[int, str] = {
    DEVICE_TYPE_SINGLE: "Switch Input",
    DEVICE_TYPE_DUAL: "Switch Input",
    DEVICE_TYPE_TRIPLE: "Switch Input",
    DEVICE_TYPE_ANALOG: "Analog",
    DEVICE_TYPE_I2C: "I2C",
    DEVICE_TYPE_SERIAL: "Serial",
    DEVICE_TYPE_SERIAL_PLUS1: "Serial",
    DEVICE_TYPE_SPI: "SPI",
    DEVICE_TYPE_SPI2: "SPI",
    DEVICE_TYPE_SPI3: "SPI",
    DEVICE_TYPE_CUSTOM0: "Custom",
    DEVICE_TYPE_CUSTOM1: "Custom",
    DEVICE_TYPE_CUSTOM2: "Custom",
    DEVICE_TYPE_CUSTOM3: "Custom",
    DEVICE_TYPE_USB: "USB HID",
    DEVICE_TYPE_DUMMY: "Internal",
}

RPI_MODEL_USABLE_GPIO: list[tuple[str, set[int]]] = [
    ("pi 1 model a+", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi 1 model b+", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi 1 model a", {2, 3, 4, 7, 8, 9, 10, 11, 14, 15, 17, 18, 22, 23, 24, 25, 27, 28, 29, 30, 31}),
    ("pi 1 model b rev 2", {2, 3, 4, 7, 8, 9, 10, 11, 14, 15, 17, 18, 22, 23, 24, 25, 27, 28, 29, 30, 31}),
    ("pi 1 model b rev 1", {0, 1, 4, 7, 8, 9, 10, 11, 14, 15, 17, 18, 21, 22, 23, 24, 25}),
    ("pi 2 model b", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi 3 model b+", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi 3 model b", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi 4 model b", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi 5", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi zero 2 w", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi zero w", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
    ("pi zero", {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}),
]

_RPI_USABLE_GPIO_CACHE: set[int] | None = None
_IS_RPI_CACHE: bool | None = None


def is_raspberry_pi() -> bool:
    global _IS_RPI_CACHE
    if _IS_RPI_CACHE is not None:
        return _IS_RPI_CACHE
    try:
        with open("/proc/device-tree/model") as f:
            model = f.read().strip("\x00").strip()
    except Exception:
        _IS_RPI_CACHE = False
        return False
    _IS_RPI_CACHE = "raspberry" in model.lower()
    return _IS_RPI_CACHE


def _detect_rpi_usable_gpios() -> set[int]:
    global _RPI_USABLE_GPIO_CACHE
    if _RPI_USABLE_GPIO_CACHE is not None:
        return _RPI_USABLE_GPIO_CACHE
    try:
        with open("/proc/device-tree/model") as f:
            model = f.read().strip("\x00").strip().lower()
    except Exception:
        _RPI_USABLE_GPIO_CACHE = set(range(28))
        return _RPI_USABLE_GPIO_CACHE
    for pattern, gpios in RPI_MODEL_USABLE_GPIO:
        if pattern in model:
            _RPI_USABLE_GPIO_CACHE = gpios
            return gpios
    _RPI_USABLE_GPIO_CACHE = set(range(28))
    return _RPI_USABLE_GPIO_CACHE


RPI_USABLE_GPIO = _detect_rpi_usable_gpios()
RPI_GPIO_COUNT = max(RPI_USABLE_GPIO) + 1 if RPI_USABLE_GPIO else 28

RPI_SPECIAL_GPIO: dict[int, str] = {
    0: "I2C0 SDA",
    1: "I2C0 SCL",
    2: "I2C1 SDA (HAT ID)",
    3: "I2C1 SCL (HAT ID)",
    8: "SPI0 CE0",
    9: "SPI0 MISO",
    10: "SPI0 MOSI",
    11: "SPI0 SCLK",
    14: "UART TX",
    15: "UART RX",
}

SENSOR_TYPE_NONE = 0
SENSOR_TYPE_SINGLE = 1
SENSOR_TYPE_TEMP_HUM = 2
SENSOR_TYPE_TEMP_BARO = 3
SENSOR_TYPE_TEMP_HUM_BARO = 4
SENSOR_TYPE_DUAL = 5
SENSOR_TYPE_TRIPLE = 6
SENSOR_TYPE_QUAD = 7
SENSOR_TYPE_TEMP_EMPTY_BARO = 8
SENSOR_TYPE_SWITCH = 10
SENSOR_TYPE_DIMMER = 11
SENSOR_TYPE_ULONG = 20
SENSOR_TYPE_WIND = 21
SENSOR_TYPE_STRING = 22
SENSOR_TYPE_UINT32_DUAL = 31
SENSOR_TYPE_UINT32_TRIPLE = 32
SENSOR_TYPE_UINT32_QUAD = 33
SENSOR_TYPE_INT32_SINGLE = 40
SENSOR_TYPE_INT32_DUAL = 41
SENSOR_TYPE_INT32_TRIPLE = 42
SENSOR_TYPE_INT32_QUAD = 43
SENSOR_TYPE_UINT64_SINGLE = 50
SENSOR_TYPE_UINT64_DUAL = 51
SENSOR_TYPE_INT64_SINGLE = 60
SENSOR_TYPE_INT64_DUAL = 61
SENSOR_TYPE_DOUBLE_SINGLE = 70
SENSOR_TYPE_DOUBLE_DUAL = 71
SENSOR_TYPE_ANALOG_ONLY = 100
SENSOR_TYPE_TEMP_ONLY = 101
SENSOR_TYPE_HUM_ONLY = 102
SENSOR_TYPE_LUX_ONLY = 103
SENSOR_TYPE_DISTANCE_ONLY = 104
SENSOR_TYPE_DIRECTION_ONLY = 105
SENSOR_TYPE_PM2_5_ONLY = 106
SENSOR_TYPE_PM1_0_ONLY = 107
SENSOR_TYPE_PM10_ONLY = 108
SENSOR_TYPE_MOISTURE_ONLY = 109
SENSOR_TYPE_CO2_ONLY = 110
SENSOR_TYPE_GPS_ONLY = 111
SENSOR_TYPE_UV_ONLY = 112
SENSOR_TYPE_UV_INDEX_ONLY = 113
SENSOR_TYPE_IR_ONLY = 114
SENSOR_TYPE_WEIGHT_ONLY = 115
SENSOR_TYPE_VOLTAGE_ONLY = 116
SENSOR_TYPE_CURRENT_ONLY = 117
SENSOR_TYPE_POWER_USG_ONLY = 118
SENSOR_TYPE_POWER_FACT_ONLY = 119
SENSOR_TYPE_APPRNT_POWER_USG_ONLY = 120
SENSOR_TYPE_TVOC_ONLY = 121
SENSOR_TYPE_BARO_ONLY = 122
SENSOR_TYPE_COLOR_RED_ONLY = 123
SENSOR_TYPE_COLOR_GREEN_ONLY = 124
SENSOR_TYPE_COLOR_BLUE_ONLY = 125
SENSOR_TYPE_COLOR_TEMP_ONLY = 126
SENSOR_TYPE_REACTIVE_POWER_ONLY = 127
SENSOR_TYPE_AQI_ONLY = 128
SENSOR_TYPE_NOX_ONLY = 129
SENSOR_TYPE_SWITCH_INVERTED = 130
SENSOR_TYPE_WIND_SPEED = 131
SENSOR_TYPE_DURATION = 132
SENSOR_TYPE_DATE = 133
SENSOR_TYPE_TIMESTAMP = 134
SENSOR_TYPE_DATA_RATE = 135
SENSOR_TYPE_DATA_SIZE = 136
SENSOR_TYPE_SOUND_PRESSURE = 137
SENSOR_TYPE_SIGNAL_STRENGTH = 138
SENSOR_TYPE_REACTIVE_ENERGY = 139
SENSOR_TYPE_FREQUENCY = 140
SENSOR_TYPE_ENERGY = 141
SENSOR_TYPE_ENERGY_STORAGE = 142
SENSOR_TYPE_ABS_HUMIDITY = 143
SENSOR_TYPE_ATMOS_PRESSURE = 144
SENSOR_TYPE_BLOOD_GLUCOSE_C = 145
SENSOR_TYPE_CO_ONLY = 146
SENSOR_TYPE_ENERGY_DISTANCE = 147
SENSOR_TYPE_GAS_ONLY = 148
SENSOR_TYPE_NITROUS_OXIDE = 149
SENSOR_TYPE_OZONE_ONLY = 150
SENSOR_TYPE_PRECIPITATION = 151
SENSOR_TYPE_PRECIPITATION_INTEN = 152
SENSOR_TYPE_SULPHUR_DIOXIDE = 153
SENSOR_TYPE_VOC_PARTS = 154
SENSOR_TYPE_VOLUME = 155
SENSOR_TYPE_VOLUME_FLOW_RATE = 156
SENSOR_TYPE_VOLUME_STORAGE = 157
SENSOR_TYPE_WATER = 158
SENSOR_TYPE_NOT_SET = 255

# Sensor_VType for Home Assistant MQTT Discovery
# Values from ESPEasy Sensor_VType enum
SENSOR_V_TYPE_NONE = 0
SENSOR_V_TYPE_SINGLE = 1
SENSOR_V_TYPE_TEMP = 2
SENSOR_V_TYPE_HUM = 3
SENSOR_V_TYPE_BARO = 4
SENSOR_V_TYPE_TEMP_HUM = 5
SENSOR_V_TYPE_TEMP_BARO = 6
SENSOR_V_TYPE_TEMP_HUM_BARO = 7
SENSOR_V_TYPE_WIND = 8
SENSOR_V_TYPE_RAIN = 9
SENSOR_V_TYPE_UV = 10
SENSOR_V_TYPE_LEVEL = 11
SENSOR_V_TYPE_ILLUMINANCE = 12
SENSOR_V_TYPE_DIRECTION = 13
SENSOR_V_TYPE_SPEED = 14
SENSOR_V_TYPE_DISTANCE = 15
SENSOR_V_TYPE_CO2 = 16
SENSOR_V_TYPE_DIMMER = 17
SENSOR_V_TYPE_PRESSURE = 18
SENSOR_V_TYPE_WATT = 19
SENSOR_V_TYPE_KWH = 20
SENSOR_V_TYPE_VAR = 21
SENSOR_V_TYPE_VA = 22
SENSOR_V_TYPE_FACTOR = 23
SENSOR_V_TYPE_ENERGY = 24
SENSOR_V_TYPE_CURRENT = 25
SENSOR_V_TYPE_VOLTAGE = 26
SENSOR_V_TYPE_SWITCH = 27
SENSOR_V_TYPE_CONTACT = 28
SENSOR_V_TYPE_VIBRATION = 29
SENSOR_V_TYPE_WEIGHT = 30
SENSOR_V_TYPE_TEXT = 31
SENSOR_V_TYPE_PM2_5 = 32
SENSOR_V_TYPE_PM10 = 33
SENSOR_V_TYPE_PM1_0 = 34
SENSOR_V_TYPE_PARTICLE_COUNT = 35
SENSOR_V_TYPE_TEMP_EMPTY_BARO = 36
SENSOR_V_TYPE_GAS = 37
SENSOR_V_TYPE_MQTT_IMPORT = 38
SENSOR_V_TYPE_AQI = 39
SENSOR_V_TYPE_NOX = 40
SENSOR_V_TYPE_PM1_0_PM2_5_PM10 = 41
SENSOR_V_TYPE_WATER_FLOW = 42
SENSOR_V_TYPE_ENERGY_DISTANCE = 43
SENSOR_V_TYPE_SIGNAL = 44
SENSOR_V_TYPE_DURATION = 45
SENSOR_V_TYPE_SPECIAL = 99
SENSOR_V_TYPE_DUAL = 100
SENSOR_V_TYPE_TRIPLE = 101
SENSOR_V_TYPE_QUAD = 102

SENSOR_V_TYPE_CAN_SET = 0x0100

SENSOR_TYPE_TO_DISCOVERY_VTYPES: dict[int, list[int]] = {
    SENSOR_TYPE_NONE: [],
    SENSOR_TYPE_SINGLE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_TEMP_HUM: [SENSOR_V_TYPE_TEMP, SENSOR_V_TYPE_HUM],
    SENSOR_TYPE_TEMP_BARO: [SENSOR_V_TYPE_TEMP, SENSOR_V_TYPE_BARO],
    SENSOR_TYPE_TEMP_HUM_BARO: [SENSOR_V_TYPE_TEMP, SENSOR_V_TYPE_HUM, SENSOR_V_TYPE_BARO],
    SENSOR_TYPE_DUAL: [SENSOR_V_TYPE_DUAL, SENSOR_V_TYPE_DUAL],
    SENSOR_TYPE_TRIPLE: [SENSOR_V_TYPE_TRIPLE, SENSOR_V_TYPE_TRIPLE, SENSOR_V_TYPE_TRIPLE],
    SENSOR_TYPE_QUAD: [SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD],
    SENSOR_TYPE_TEMP_EMPTY_BARO: [SENSOR_V_TYPE_TEMP, SENSOR_V_TYPE_BARO],
    SENSOR_TYPE_SWITCH: [SENSOR_V_TYPE_SWITCH],
    SENSOR_TYPE_DIMMER: [SENSOR_V_TYPE_DIMMER],
    SENSOR_TYPE_ULONG: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_WIND: [SENSOR_V_TYPE_WIND],
    SENSOR_TYPE_STRING: [SENSOR_V_TYPE_TEXT],
    SENSOR_TYPE_UINT32_DUAL: [SENSOR_V_TYPE_DUAL, SENSOR_V_TYPE_DUAL],
    SENSOR_TYPE_UINT32_TRIPLE: [SENSOR_V_TYPE_TRIPLE, SENSOR_V_TYPE_TRIPLE, SENSOR_V_TYPE_TRIPLE],
    SENSOR_TYPE_UINT32_QUAD: [SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD],
    SENSOR_TYPE_INT32_SINGLE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_INT32_DUAL: [SENSOR_V_TYPE_DUAL, SENSOR_V_TYPE_DUAL],
    SENSOR_TYPE_INT32_TRIPLE: [SENSOR_V_TYPE_TRIPLE, SENSOR_V_TYPE_TRIPLE, SENSOR_V_TYPE_TRIPLE],
    SENSOR_TYPE_INT32_QUAD: [SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD, SENSOR_V_TYPE_QUAD],
    SENSOR_TYPE_UINT64_SINGLE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_UINT64_DUAL: [SENSOR_V_TYPE_DUAL, SENSOR_V_TYPE_DUAL],
    SENSOR_TYPE_INT64_SINGLE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_INT64_DUAL: [SENSOR_V_TYPE_DUAL, SENSOR_V_TYPE_DUAL],
    SENSOR_TYPE_DOUBLE_SINGLE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_DOUBLE_DUAL: [SENSOR_V_TYPE_DUAL, SENSOR_V_TYPE_DUAL],
    SENSOR_TYPE_ANALOG_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_TEMP_ONLY: [SENSOR_V_TYPE_TEMP],
    SENSOR_TYPE_HUM_ONLY: [SENSOR_V_TYPE_HUM],
    SENSOR_TYPE_LUX_ONLY: [SENSOR_V_TYPE_ILLUMINANCE],
    SENSOR_TYPE_DISTANCE_ONLY: [SENSOR_V_TYPE_DISTANCE],
    SENSOR_TYPE_DIRECTION_ONLY: [SENSOR_V_TYPE_DIRECTION],
    SENSOR_TYPE_PM2_5_ONLY: [SENSOR_V_TYPE_PM2_5],
    SENSOR_TYPE_PM1_0_ONLY: [SENSOR_V_TYPE_PM1_0],
    SENSOR_TYPE_PM10_ONLY: [SENSOR_V_TYPE_PM10],
    SENSOR_TYPE_MOISTURE_ONLY: [SENSOR_V_TYPE_LEVEL],
    SENSOR_TYPE_CO2_ONLY: [SENSOR_V_TYPE_CO2],
    SENSOR_TYPE_GPS_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_UV_ONLY: [SENSOR_V_TYPE_UV],
    SENSOR_TYPE_UV_INDEX_ONLY: [SENSOR_V_TYPE_UV],
    SENSOR_TYPE_IR_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_WEIGHT_ONLY: [SENSOR_V_TYPE_WEIGHT],
    SENSOR_TYPE_VOLTAGE_ONLY: [SENSOR_V_TYPE_VOLTAGE],
    SENSOR_TYPE_CURRENT_ONLY: [SENSOR_V_TYPE_CURRENT],
    SENSOR_TYPE_POWER_USG_ONLY: [SENSOR_V_TYPE_WATT],
    SENSOR_TYPE_POWER_FACT_ONLY: [SENSOR_V_TYPE_FACTOR],
    SENSOR_TYPE_APPRNT_POWER_USG_ONLY: [SENSOR_V_TYPE_VA],
    SENSOR_TYPE_TVOC_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_BARO_ONLY: [SENSOR_V_TYPE_PRESSURE],
    SENSOR_TYPE_COLOR_RED_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_COLOR_GREEN_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_COLOR_BLUE_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_COLOR_TEMP_ONLY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_REACTIVE_POWER_ONLY: [SENSOR_V_TYPE_VAR],
    SENSOR_TYPE_AQI_ONLY: [SENSOR_V_TYPE_AQI],
    SENSOR_TYPE_NOX_ONLY: [SENSOR_V_TYPE_NOX],
    SENSOR_TYPE_SWITCH_INVERTED: [SENSOR_V_TYPE_SWITCH],
    SENSOR_TYPE_WIND_SPEED: [SENSOR_V_TYPE_SPEED],
    SENSOR_TYPE_DURATION: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_DATE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_TIMESTAMP: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_DATA_RATE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_DATA_SIZE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_SOUND_PRESSURE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_SIGNAL_STRENGTH: [SENSOR_V_TYPE_LEVEL],
    SENSOR_TYPE_REACTIVE_ENERGY: [SENSOR_V_TYPE_ENERGY],
    SENSOR_TYPE_FREQUENCY: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_ENERGY: [SENSOR_V_TYPE_ENERGY],
    SENSOR_TYPE_ENERGY_STORAGE: [SENSOR_V_TYPE_ENERGY],
    SENSOR_TYPE_ABS_HUMIDITY: [SENSOR_V_TYPE_HUM],
    SENSOR_TYPE_ATMOS_PRESSURE: [SENSOR_V_TYPE_PRESSURE],
    SENSOR_TYPE_BLOOD_GLUCOSE_C: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_CO_ONLY: [SENSOR_V_TYPE_GAS],
    SENSOR_TYPE_ENERGY_DISTANCE: [SENSOR_V_TYPE_ENERGY_DISTANCE],
    SENSOR_TYPE_GAS_ONLY: [SENSOR_V_TYPE_GAS],
    SENSOR_TYPE_NITROUS_OXIDE: [SENSOR_V_TYPE_GAS],
    SENSOR_TYPE_OZONE_ONLY: [SENSOR_V_TYPE_GAS],
    SENSOR_TYPE_PRECIPITATION: [SENSOR_V_TYPE_RAIN],
    SENSOR_TYPE_PRECIPITATION_INTEN: [SENSOR_V_TYPE_RAIN],
    SENSOR_TYPE_SULPHUR_DIOXIDE: [SENSOR_V_TYPE_GAS],
    SENSOR_TYPE_VOC_PARTS: [SENSOR_V_TYPE_GAS],
    SENSOR_TYPE_VOLUME: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_VOLUME_FLOW_RATE: [SENSOR_V_TYPE_WATER_FLOW],
    SENSOR_TYPE_VOLUME_STORAGE: [SENSOR_V_TYPE_SINGLE],
    SENSOR_TYPE_WATER: [SENSOR_V_TYPE_WATER_FLOW],
}


def get_discovery_vtypes(sensor_type: int, num_values: int) -> list[int]:
    vtypes = SENSOR_TYPE_TO_DISCOVERY_VTYPES.get(sensor_type, [SENSOR_V_TYPE_SINGLE])
    if len(vtypes) >= num_values:
        return vtypes[:num_values]
    return vtypes + [SENSOR_V_TYPE_SINGLE] * (num_values - len(vtypes))


SENSOR_TYPE_TO_VALUE_COUNT: dict[int, int] = {
    SENSOR_TYPE_SINGLE: 1,
    SENSOR_TYPE_TEMP_HUM: 2,
    SENSOR_TYPE_TEMP_BARO: 3,
    SENSOR_TYPE_TEMP_HUM_BARO: 4,
    SENSOR_TYPE_DUAL: 2,
    SENSOR_TYPE_TRIPLE: 3,
    SENSOR_TYPE_QUAD: 4,
    SENSOR_TYPE_TEMP_EMPTY_BARO: 2,
    SENSOR_TYPE_SWITCH: 1,
    SENSOR_TYPE_DIMMER: 1,
    SENSOR_TYPE_ULONG: 1,
    SENSOR_TYPE_WIND: 1,
    SENSOR_TYPE_STRING: 1,
    SENSOR_TYPE_UINT32_DUAL: 2,
    SENSOR_TYPE_UINT32_TRIPLE: 3,
    SENSOR_TYPE_UINT32_QUAD: 4,
    SENSOR_TYPE_INT32_SINGLE: 1,
    SENSOR_TYPE_INT32_DUAL: 2,
    SENSOR_TYPE_INT32_TRIPLE: 3,
    SENSOR_TYPE_INT32_QUAD: 4,
    SENSOR_TYPE_UINT64_SINGLE: 1,
    SENSOR_TYPE_UINT64_DUAL: 2,
    SENSOR_TYPE_INT64_SINGLE: 1,
    SENSOR_TYPE_INT64_DUAL: 2,
    SENSOR_TYPE_DOUBLE_SINGLE: 1,
    SENSOR_TYPE_DOUBLE_DUAL: 2,
    SENSOR_TYPE_ANALOG_ONLY: 1,
    SENSOR_TYPE_TEMP_ONLY: 1,
    SENSOR_TYPE_HUM_ONLY: 1,
    SENSOR_TYPE_LUX_ONLY: 1,
    SENSOR_TYPE_DISTANCE_ONLY: 1,
    SENSOR_TYPE_DIRECTION_ONLY: 1,
    SENSOR_TYPE_PM2_5_ONLY: 1,
    SENSOR_TYPE_PM1_0_ONLY: 1,
    SENSOR_TYPE_PM10_ONLY: 1,
    SENSOR_TYPE_MOISTURE_ONLY: 1,
    SENSOR_TYPE_CO2_ONLY: 1,
    SENSOR_TYPE_GPS_ONLY: 1,
    SENSOR_TYPE_UV_ONLY: 1,
    SENSOR_TYPE_UV_INDEX_ONLY: 1,
    SENSOR_TYPE_IR_ONLY: 1,
    SENSOR_TYPE_WEIGHT_ONLY: 1,
    SENSOR_TYPE_VOLTAGE_ONLY: 1,
    SENSOR_TYPE_CURRENT_ONLY: 1,
    SENSOR_TYPE_POWER_USG_ONLY: 1,
    SENSOR_TYPE_POWER_FACT_ONLY: 1,
    SENSOR_TYPE_APPRNT_POWER_USG_ONLY: 1,
    SENSOR_TYPE_TVOC_ONLY: 1,
    SENSOR_TYPE_BARO_ONLY: 1,
    SENSOR_TYPE_COLOR_RED_ONLY: 1,
    SENSOR_TYPE_COLOR_GREEN_ONLY: 1,
    SENSOR_TYPE_COLOR_BLUE_ONLY: 1,
    SENSOR_TYPE_COLOR_TEMP_ONLY: 1,
    SENSOR_TYPE_REACTIVE_POWER_ONLY: 1,
    SENSOR_TYPE_AQI_ONLY: 1,
    SENSOR_TYPE_NOX_ONLY: 1,
    SENSOR_TYPE_SWITCH_INVERTED: 1,
    SENSOR_TYPE_WIND_SPEED: 1,
    SENSOR_TYPE_DURATION: 1,
    SENSOR_TYPE_DATE: 1,
    SENSOR_TYPE_TIMESTAMP: 1,
    SENSOR_TYPE_DATA_RATE: 1,
    SENSOR_TYPE_DATA_SIZE: 1,
    SENSOR_TYPE_SOUND_PRESSURE: 1,
    SENSOR_TYPE_SIGNAL_STRENGTH: 1,
    SENSOR_TYPE_REACTIVE_ENERGY: 1,
    SENSOR_TYPE_FREQUENCY: 1,
    SENSOR_TYPE_ENERGY: 1,
    SENSOR_TYPE_ENERGY_STORAGE: 1,
    SENSOR_TYPE_ABS_HUMIDITY: 1,
    SENSOR_TYPE_ATMOS_PRESSURE: 1,
    SENSOR_TYPE_BLOOD_GLUCOSE_C: 1,
    SENSOR_TYPE_CO_ONLY: 1,
    SENSOR_TYPE_ENERGY_DISTANCE: 1,
    SENSOR_TYPE_GAS_ONLY: 1,
    SENSOR_TYPE_NITROUS_OXIDE: 1,
    SENSOR_TYPE_OZONE_ONLY: 1,
    SENSOR_TYPE_PRECIPITATION: 1,
    SENSOR_TYPE_PRECIPITATION_INTEN: 1,
    SENSOR_TYPE_SULPHUR_DIOXIDE: 1,
    SENSOR_TYPE_VOC_PARTS: 1,
    SENSOR_TYPE_VOLUME: 1,
    SENSOR_TYPE_VOLUME_FLOW_RATE: 1,
    SENSOR_TYPE_VOLUME_STORAGE: 1,
    SENSOR_TYPE_WATER: 1,
}

SENSOR_TYPE_LABELS: dict[int, str] = {
    SENSOR_TYPE_NONE: "None",
    SENSOR_TYPE_SINGLE: "Single",
    SENSOR_TYPE_TEMP_HUM: "Temp / Hum",
    SENSOR_TYPE_TEMP_BARO: "Temp / Baro",
    SENSOR_TYPE_TEMP_HUM_BARO: "Temp / Hum / Baro",
    SENSOR_TYPE_DUAL: "Dual",
    SENSOR_TYPE_TRIPLE: "Triple",
    SENSOR_TYPE_QUAD: "Quad",
    SENSOR_TYPE_TEMP_EMPTY_BARO: "Temp / - / Baro",
    SENSOR_TYPE_SWITCH: "Switch",
    SENSOR_TYPE_DIMMER: "Dimmer",
    SENSOR_TYPE_ULONG: "UInt32 (1x)",
    SENSOR_TYPE_WIND: "Wind",
    SENSOR_TYPE_STRING: "String",
    SENSOR_TYPE_UINT32_DUAL: "UInt32 (2x)",
    SENSOR_TYPE_UINT32_TRIPLE: "UInt32 (3x)",
    SENSOR_TYPE_UINT32_QUAD: "UInt32 (4x)",
    SENSOR_TYPE_INT32_SINGLE: "Int32 (1x)",
    SENSOR_TYPE_INT32_DUAL: "Int32 (2x)",
    SENSOR_TYPE_INT32_TRIPLE: "Int32 (3x)",
    SENSOR_TYPE_INT32_QUAD: "Int32 (4x)",
    SENSOR_TYPE_UINT64_SINGLE: "UInt64 (1x)",
    SENSOR_TYPE_UINT64_DUAL: "UInt64 (2x)",
    SENSOR_TYPE_INT64_SINGLE: "Int64 (1x)",
    SENSOR_TYPE_INT64_DUAL: "Int64 (2x)",
    SENSOR_TYPE_DOUBLE_SINGLE: "Double (1x)",
    SENSOR_TYPE_DOUBLE_DUAL: "Double (2x)",
    SENSOR_TYPE_ANALOG_ONLY: "Analog",
    SENSOR_TYPE_TEMP_ONLY: "Temp",
    SENSOR_TYPE_HUM_ONLY: "Hum",
    SENSOR_TYPE_LUX_ONLY: "Lux",
    SENSOR_TYPE_DISTANCE_ONLY: "Distance",
    SENSOR_TYPE_DIRECTION_ONLY: "Direction",
    SENSOR_TYPE_PM2_5_ONLY: "Dust PM2.5",
    SENSOR_TYPE_PM1_0_ONLY: "Dust PM1.0",
    SENSOR_TYPE_PM10_ONLY: "Dust PM10",
    SENSOR_TYPE_MOISTURE_ONLY: "Moisture",
    SENSOR_TYPE_CO2_ONLY: "(e)CO2",
    SENSOR_TYPE_GPS_ONLY: "GPS",
    SENSOR_TYPE_UV_ONLY: "UV",
    SENSOR_TYPE_UV_INDEX_ONLY: "UV Index",
    SENSOR_TYPE_IR_ONLY: "IR",
    SENSOR_TYPE_WEIGHT_ONLY: "Weight",
    SENSOR_TYPE_VOLTAGE_ONLY: "Voltage",
    SENSOR_TYPE_CURRENT_ONLY: "Current",
    SENSOR_TYPE_POWER_USG_ONLY: "Power Usage",
    SENSOR_TYPE_POWER_FACT_ONLY: "Power Factor",
    SENSOR_TYPE_APPRNT_POWER_USG_ONLY: "Apparent Power",
    SENSOR_TYPE_TVOC_ONLY: "TVOC",
    SENSOR_TYPE_BARO_ONLY: "Baro",
    SENSOR_TYPE_COLOR_RED_ONLY: "Red",
    SENSOR_TYPE_COLOR_GREEN_ONLY: "Green",
    SENSOR_TYPE_COLOR_BLUE_ONLY: "Blue",
    SENSOR_TYPE_COLOR_TEMP_ONLY: "Color temperature",
    SENSOR_TYPE_REACTIVE_POWER_ONLY: "Reactive Power",
    SENSOR_TYPE_AQI_ONLY: "AQI",
    SENSOR_TYPE_NOX_ONLY: "NOx",
    SENSOR_TYPE_SWITCH_INVERTED: "Switch (inv.)",
    SENSOR_TYPE_WIND_SPEED: "Wind speed",
    SENSOR_TYPE_DURATION: "Duration",
    SENSOR_TYPE_DATE: "Date",
    SENSOR_TYPE_TIMESTAMP: "Timestamp",
    SENSOR_TYPE_DATA_RATE: "Data rate",
    SENSOR_TYPE_DATA_SIZE: "Data size",
    SENSOR_TYPE_SOUND_PRESSURE: "Sound pressure",
    SENSOR_TYPE_SIGNAL_STRENGTH: "Signal strength",
    SENSOR_TYPE_REACTIVE_ENERGY: "Reactive Energy",
    SENSOR_TYPE_FREQUENCY: "Frequency",
    SENSOR_TYPE_ENERGY: "Energy",
    SENSOR_TYPE_ENERGY_STORAGE: "Energy storage",
    SENSOR_TYPE_ABS_HUMIDITY: "Absolute humidity",
    SENSOR_TYPE_ATMOS_PRESSURE: "Atmospheric pressure",
    SENSOR_TYPE_BLOOD_GLUCOSE_C: "Blood glucose conc.",
    SENSOR_TYPE_CO_ONLY: "CO",
    SENSOR_TYPE_ENERGY_DISTANCE: "Energy distance",
    SENSOR_TYPE_GAS_ONLY: "Gas",
    SENSOR_TYPE_NITROUS_OXIDE: "N2O",
    SENSOR_TYPE_OZONE_ONLY: "Ozone",
    SENSOR_TYPE_PRECIPITATION: "Precipitation",
    SENSOR_TYPE_PRECIPITATION_INTEN: "Precipitation inten.",
    SENSOR_TYPE_SULPHUR_DIOXIDE: "SO2",
    SENSOR_TYPE_VOC_PARTS: "VOC parts",
    SENSOR_TYPE_VOLUME: "Volume",
    SENSOR_TYPE_VOLUME_FLOW_RATE: "Volume flow rate",
    SENSOR_TYPE_VOLUME_STORAGE: "Volume storage",
    SENSOR_TYPE_WATER: "Water cons.",
    SENSOR_TYPE_NOT_SET: "Not set",
}

LOG_LEVEL_NONE = 0
LOG_LEVEL_ERROR = 1
LOG_LEVEL_INFO = 2
LOG_LEVEL_DEBUG = 3
LOG_LEVEL_DEBUG_MORE = 4
LOG_LEVEL_DEBUG_DEV = 9

class LogDestination:
    SERIAL = 0
    SYSLOG = 1
    WEBLOG = 2
    SDCARD = 3

PIN_MODE_UNDEFINED = 0
PIN_MODE_INPUT = 1
PIN_MODE_OUTPUT = 2
PIN_MODE_PWM = 3
PIN_MODE_SERVO = 4
PIN_MODE_INPUT_PULLUP = 5
PIN_MODE_OFFLINE = 6
PIN_MODE_INPUT_PULLDOWN = 7

GPIO_TYPE_INVALID = 0
GPIO_TYPE_INTERNAL = 1
GPIO_TYPE_MCP = 2
GPIO_TYPE_PCF = 3

class NetworkMedium:
    WIFI = 0
    ETHERNET = 1
    NOT_SET = 255

class DeviceModel:
    DEFAULT = 0
    SONOFF_BASIC = 1
    SONOFF_TH1X = 2
    SONOFF_S2X = 3
    SONOFF_TOUCH_T1 = 4
    SONOFF_TOUCH_T2 = 5
    SONOFF_TOUCH_T3 = 6
    SONOFF_4CH = 7
    SONOFF_POW = 8
    SONOFF_POWR2 = 9
    SHELLY1 = 10
    SHELLY_PLUG_S = 11

class TimeSource:
    GPS_PPS = 5
    GPS = 10
    NTP = 15
    MANUAL_SET = 20
    ESP_NOW_PEER = 40
    ESPEASY_P2P_UDP = 41
    EXTERNAL_RTC = 45
    GPS_NO_FIX = 46
    RESTORE_RTC = 50
    NO_TIME_SOURCE = 255

UOM_NONE = 0
UOM_DEGC = 1
UOM_DEGF = 2
UOM_K = 3
UOM_PERCENT = 4
UOM_PA = 5
UOM_HPA = 6
UOM_BAR = 7
UOM_MBAR = 8
UOM_INHG = 9
UOM_PSI = 10
UOM_W = 11
UOM_KW = 12
UOM_V = 13
UOM_WH = 14
UOM_KWH = 15
UOM_A = 16
UOM_VA = 17
UOM_MM = 18
UOM_CM = 19
UOM_M = 20
UOM_KM = 21
UOM_L = 22
UOM_ML = 23
UOM_M3 = 24
UOM_FT3 = 25
UOM_M3H = 26
UOM_FT3H = 27
UOM_LUX = 28
UOM_UV_INDEX = 29
UOM_UGM3 = 30
UOM_MGM3 = 31
UOM_PM3 = 32
UOM_PPM = 33
UOM_PPB = 34
UOM_DEG = 35
UOM_EUR = 36
UOM_USD = 37
UOM_CENT = 38
UOM_US = 39
UOM_MS = 40
UOM_S = 41
UOM_MIN = 42
UOM_H = 43
UOM_D = 44
UOM_WEEK = 45
UOM_MONTH = 46
UOM_Y = 47
UOM_IN = 48
UOM_FT = 49
UOM_YD = 50
UOM_MI = 51
UOM_HZ = 52
UOM_GHZ = 53
UOM_GAL = 54
UOM_FL_OZ = 55
UOM_M2 = 56
UOM_G = 57
UOM_KG = 58
UOM_MG = 59
UOM_UG = 60
UOM_OZ = 61
UOM_LB = 62
UOM_US_CM = 63
UOM_WM2 = 64
UOM_MMH = 65
UOM_MMS = 66
UOM_IN_S = 67
UOM_MS = 68
UOM_IN_H = 69
UOM_KMH = 70
UOM_MPH = 71
UOM_DB = 72
UOM_DBM = 73
UOM_BIT = 74
UOM_KBIT = 75
UOM_MBIT = 76
UOM_GBIT = 77
UOM_B = 78
UOM_KB = 79
UOM_MB = 80
UOM_GB = 81
UOM_TB = 82
UOM_PB = 83
UOM_EB = 84
UOM_ZB = 85
UOM_YB = 86
UOM_KIB = 87
UOM_MIB = 88
UOM_GIB = 89
UOM_TIB = 90
UOM_PIB = 91
UOM_EIB = 92
UOM_ZIB = 93
UOM_YIB = 94
UOM_BIT_S = 95
UOM_KBIT_S = 96
UOM_MBIT_S = 97
UOM_GBIT_S = 98
UOM_BS = 99
UOM_KBS = 100
UOM_MBS = 101
UOM_GBS = 102
UOM_KIB_S = 103
UOM_MIB_S = 104
UOM_GIB_S = 105
UOM_FT_S = 106
UOM_KN = 107
UOM_MW = 108
UOM_MEGAW = 109
UOM_GW = 110
UOM_TW = 111
UOM_BTU = 112
UOM_PH = 113
UOM_CBAR = 114
UOM_MMHG = 115
UOM_KPA = 116
UOM_MA = 117
UOM_UA = 118
UOM_MV = 119
UOM_UV = 120
UOM_KV = 121
UOM_CM2 = 122
UOM_KM2 = 123
UOM_MM2 = 124
UOM_IN2 = 125
UOM_FT2 = 126
UOM_YD2 = 127
UOM_MI2 = 128
UOM_AC = 129
UOM_HA = 130
UOM_KHZ = 131
UOM_MHZ = 132
UOM_MWH = 133
UOM_MEGWH = 134
UOM_GWH = 135
UOM_TWH = 136
UOM_CAL = 137
UOM_KCAL = 138
UOM_MCAL = 139
UOM_GCAL = 140
UOM_J = 141
UOM_KJ = 142
UOM_MJ = 143
UOM_GJ = 144
UOM_VAR = 145
UOM_KVAR = 146
UOM_VARH = 147
UOM_KVARH = 148
UOM_ST = 149
UOM_MG_DL = 150
UOM_MMOL_L = 151
UOM_USV = 152
UOM_USVH = 153
UOM_M3S = 154
UOM_FT3_MIN = 155
UOM_LH = 156
UOM_LMIN = 157
UOM_LS = 158
UOM_GAL_MIN = 159
UOM_MLS = 160
UOM_GM3 = 161
UOM_KWH_100KM = 162
UOM_WH_KM = 163
UOM_MI_KWH = 164
UOM_KM_KWH = 165
UOM_IN_D = 166
UOM_MM_D = 167
UOM_AH = 168

# --- System / Default constants ---

BUILD_EPOCH = datetime(1967, 4, 29)
BUILD = 21595


def build_to_date_str(build: int) -> str:
    return (BUILD_EPOCH + timedelta(days=build)).strftime("%Y-%m-%d")

DEFAULT_NAME = "MyRPIEasyDevice"
UNIT = 0

DEFAULT_PUB = "sensors/rpieasy/%sysname%/%tskname%/%valname%"
DEFAULT_SUB = "sensors/rpieasy/%sysname%/#"

DEFAULT_WEB_LOG_LEVEL = LOG_LEVEL_INFO

DEFAULT_WEB_PORT = 80
BACKUP_WEB_PORT = 8080
DEFAULT_P2P_PORT = 8266
DEFAULT_MQTT_PORT = 1883
DEFAULT_DOMOTICZ_PORT = 8080
DEFAULT_SMTP_PORT = 587

DEFAULT_I2C_BUS = 1
DEFAULT_I2C_SPEED = 100000
DEFAULT_SPI_SPEED = 500000
DEFAULT_FTDI_SPI_SPEED = 6000000

GOOGLE_DNS = "8.8.8.8"
DNS_QUERY_PORT = 80

P2P_BROADCAST_INTERVAL = 30
P2P_NODE_TIMEOUT = 120
P2P_CLEANUP_INTERVAL = 15

PERIODIC_TICK_INTERVAL = 1.0

TOTAL_TASK_SLOTS = 32
TASKS_PER_PAGE = 8
NUM_CONTROLLER_SLOTS = 3
NUM_TASK_VALUES = 4

DEFAULT_TASK_INTERVAL = 60
DEFAULT_CONTROLLER_TIMEOUT = 10
DEFAULT_QUEUE_DEPTH = 100
DEFAULT_QUEUE_RETRIES = 3

LOG_BUFFER_MAXLEN = 40
LOG_TTL = 2000
FILE_CHUNK_SIZE = 65536
RESTART_DELAY = 1
SECONDS_PER_DAY = 86400
SECONDS_PER_HOUR = 3600
MB_FACTOR = 1048576


_local_ip: str | None = None
_local_ip_last_refresh: float = 0.0


def get_local_ip() -> str:
    global _local_ip, _local_ip_last_refresh
    now = time.time()
    if _local_ip is not None and now - _local_ip_last_refresh < 60:
        return _local_ip
    import fcntl
    import socket
    import struct
    try:
        result = __import__("subprocess").run(["hostname", "-I"], capture_output=True, text=True, timeout=2)
        if result.returncode == 0 and result.stdout.strip():
            ips = result.stdout.strip().split()
            for ip in ips:
                ip = ip.strip()
                if ip and not ip.startswith("127.") and "." in ip:
                    _local_ip = ip
                    _local_ip_last_refresh = now
                    return _local_ip
    except Exception:
        pass
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        max_iface = 32
        buf = struct.pack("i", max_iface * 32)
        buf = fcntl.ioctl(s.fileno(), 0x8912, buf)
        buflen = struct.unpack("i", buf[:4])[0]
        data = buf[4:4 + buflen]
        for i in range(0, buflen, 32):
            ip_raw = data[i + 20:i + 24]
            ip = socket.inet_ntoa(ip_raw)
            if not ip.startswith("127."):
                s.close()
                _local_ip = ip
                _local_ip_last_refresh = now
                return _local_ip
        s.close()
    except Exception:
        pass
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        if ip and not ip.startswith("127."):
            _local_ip = ip
            _local_ip_last_refresh = now
            return _local_ip
    except Exception:
        pass
    return "-"
